### ISSUE TITLE
Allow accesslint to comment without personal access token on public repos

### ISSUE THREAD

**Issue by maya** [accesslint/accesslint-ci#28]
We'd like to use accesslint on various public repos at [18F](https://github.com/18F/), but we're not able to provide an access token due to our restrictive GitHub permissions policy. Can we allow accesslint to comment without personal access token?

@ckundo Is there any progress on this issue and standing up a standalone service to post comments on public repos?

**Comment by ckundo** [comment]
Hi Maya! Thank you for the note, that's super exciting. @tysongach and I are talking about streamlining setup today in fact, and will post notes. We're pretty far along with a standalone service, and will post that too.

**Comment by tysongach** [comment]
@maya Woo!! Our goal is to make it as easy as Hound is to setup, with a very similar workflow to do so.

**Comment by ckundo** [comment]
Hi @maya, we've release [v0.2.4](https://github.com/accesslint/accesslint-ci/releases/tag/v0.2.4), which allows accesslint-bot to comment through the accesslint.com API, instead of commenting as a project collaborator directly.

This new version requires OAuth at https://accesslint.com, and that you set the resulting accessint API token as an environment variable in CircleCI. See the readme for the env variables you'll need:

```
machine:
  environment:
    CIRCLE_TOKEN: <CircleCI API token>
    ACCESSLINT_TOKEN: <API token from https://accesslint.com>
    ACCESSLINT_GITHUB_USER: <GitHub user that authenticated at https://accesslint.com>
```

You can also add these variables directly to the CI environment via CircleCI project settings at https://circleci.com/gh/<user>/<project>/edit#env-vars.

Comment or let us know in accesslint.slack.com if you have questions!
