### ISSUE TITLE
Accesslint should be able to ignore code

### ISSUE THREAD

**Issue by gemfarmer** [AccessLint/accesslint-ci#57]
It would be nice to be able to specify code that you wanted accesslint to ignore in a scan. I could imagine this done one of several ways:

Inline: 

```html
<!-- accesslint:ignore -->
<h1>How to write inaccessible code</h1>
<!-- accesslint:endignore -->
```

Config file (for whole documents):

```yaml
# .accesslint.yml

rules:
  ignore:
    - file/path/to/file/
```

In circle.yml (for whole documents):

```yaml
# circle.yml

- bundle exec accesslint-ci ignore <name of file>
- bundle exec jekyll serve --detach
- bundle exec accesslint-ci scan https://localhost:4000
```

cc @maya
